package com.kmarinos.hermes.emailservice.model;

public enum ProcessingStage {
  REQUESTED, ACCEPTED_ATTACHMENTS,PROCESSING_ATTACHMENTS,COMPLETED_ATTACHMENTS,ACCEPTED_EMAIL, DECLINED_ATTACHMENTS,DECLINED_EMAIL, PROCESSING_EMAIL, COMPLETED_EMAIL,COMPLETED, ABORTED
}
